# obstacle center, shape and radius
Obstacles:
  Circle: 
    obs_shape: 'Circle'
    obs_radius: [0.5,0.5,0.5]
    obs_center: [[2.5,2.0],[10,2.2],[16.5,2.0]]
  
  Circle_linear: 
    obs_shape: 'Circle'
    obs_radius: [0.3]
    obs_center: [[1.5,1.5],[3.5,3.0],[5,4.25],[6.25,6.25]]

  Circle_exploration: 
    obs_shape: 'Circle'
    obs_radius: [0.3]
    obs_center: [[3,2.0],[7,2.0]]

  Circle_LM:
    obs_shape: 'Circle'
    obs_radius: [0.5]
    # obs_center: [[2.0, 3.5], [3.5, 2.0], [4.0, 2.5], [2.5, 4.0], [3.25, 4.25], [4.25, 3.25], [4.0, 4.0]]
    obs_center: [[3.65,6.65],[4.75,7.75],[7.75,4.75],[6.65,3.65],[8.25,6.25],[6.25,8.25],[7.75,7.75]]

  Circle_scattered:
    obs_shape: 'Circle'
    obs_radius: [0.5]
    obs_center: [[9,8],[7,10],[14,10],[15,15],[9,13],[13,13],[16,12],[12,8]]

